### PR TITLE
changed: skip quota checks for empty server URLs

### PR DESCRIPTION
**Pull request by jnm**
The quota mechanism expects linked server URLs to be specified and cannot do any meaningful checking when they are not.

Skipping these checks also avoids some `keys` queries that can leave the Redis server stuck consuming 100% of CPU and unable to serve other requests.

### CODE REVIEW

**Comment by MartijnR** [comment]
Ah wow, that's a big bug. Thanks for figuring this out. The thing is the quotas are basically only important when serverURL is not specified in the config (= possibly running a SaaS service), but that requires knowledge of a proprietary extension. I have to check if the account.linkedServer check needs tweaking for this to continue to work (with multiple accounts).

So this is now in my lap!

**Comment by MartijnR** [comment]
Hi John, I've made some small changes in the if statements to facilitate the little SaaS service. Would you mind doing a quick sanity check before merging?

**Comment by MartijnR** [comment]
@jnm, I cannot request you as a reviewer (because it's your PR).

**Comment by jnm** [comment]
oooh, failed by 1 millisecond :joy:
```
  414 passing (4s)
  1 failing

  1) Cache Model
       expiration
         is reset to the original expiration every time the cache item is accessed :

      AssertionError: expected 2591999001 to be at most 2591999000
      + expected - actual

      -2591999001
      +2591999000
      
    at /home/travis/build/enketo/enketo-express/node_modules/chai-as-promised/lib/chai-as-promised.js:302:22
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function.all (<anonymous>:null:null)
```

**Comment by MartijnR** [comment]
Yes, that's a poorly written test.... :)

**Pull request merged**
