### PR TITLE
Move node-sass and grunt-sass back out of devDependencies into dependencies

### PR DESCRIPTION
**Pull request by MartijnR**
Just moved some devDependencies to dependencies so `npm install --production` can deploy a production server.

Fixes regression in https://github.com/enketo/enketo-express/commit/0f338b063000b4ac8b02403923ca1a61d4247ea9 (for node-sass and grunt-sass)

### CODE REVIEW

**Comment by eyelidlessness** [comment]
I wonder if this is really necessary? The way we've been doing this is:

```sh
npm install # This of course installs dev dependencies, to enable the build
grunt
npm prune --production # This then removes those dev dependencies
```

Would that work? We could add a script to automate this process if that's preferred. Or is the intent to remove the need for that last step?

**Comment by MartijnR** [comment]
Historically, we've used `npm --production` to install a production server without pruning. This is faster too.

P.S. I think running `grunt` separately should not be necessary.

I guess the question is what is the common NodeJS way.

**Comment by eyelidlessness** [comment]
> Historically, we've used `npm --production` to install a production server without pruning. This is faster too.
> 
> I guess the question is what is the common NodeJS way.

I think the root of this is that most Node packages are distributed **after being built**, typically but not always before publishing to NPM. This is the case for the other Enketo packages used in enketo-express, which is why it hasn't been an issue for them. Whereas enketo-express is distributed, well, _here_ prior to being built.

There's some difference of opinions about how to handle this case, but my instinct is still to err on the side of keeping build tooling out of the production dependencies list. Shipping those to production already increases security risk, just by adding more stuff to the build.

That risk could increase significantly, if an NPM RFC[^1] to allow "audit assertions" is approved. That RFC proposes that package maintainers can assert that their packages aren't affected by certain vulnerabilities which would otherwise be reported in `npm audit`—and those reports would also be hidden from direct and transitive dependents. One of the specific use cases cited is for maintainers of build tooling, who don't expect their packages to be included in production builds.

[^1]: I'm not linking to it because I think it's a really bad idea.

As an alternative proposal, what if we eliminate the chicken and egg problem. I usually prefer not to commit build artifacts, but we already do with `build-docs` so there's precedent. What if we do the same with the build product of enketo-express as well? We can (should) add a CI check to validate that it hasn't been tampered with, and a note in docs about it. But otherwise this would allow us to keep distributing the same way, and only require `npm install --production`.

A slight variation of that alternative would be to automate it in CI (or, ugh, a commit hook), but that would add more complexity and potential for mistakes.

> P.S. I think running `grunt` separately should not be necessary.

I think you're right! Thanks for noticing, removing that would definitely help speed things up.

**Comment by lognaturel** [comment]
> we already do with build-docs 

Side note that I've been waiting for a good moment to ask whether we could stop doing that.

I don't have strong feelings here since I don't spend a lot of time in the broader node ecosystem. But spiritually it makes sense to me not to packages used for build in production.

**Comment by MartijnR** [comment]
Thanks to you both! I'm okay with moving the build tools from dependencies, and adding a prune step. I'll update the blog post with that. 

We still have some dynamicness in both the built css (base path, widgets) and js files (widgets at least), so I think we probably shouldn't distribute the built files.

**Comment by MartijnR** [comment]
(can be closed I think, but am leaving open in case discussion continues)

**Comment by eyelidlessness** [comment]
Thanks @MartijnR, closing since this seems settled for now.

**Pull request closed without merging**
