### PR TITLE
Prepare for 3.0.5

### PR DESCRIPTION
**Pull request by eyelidlessness**
**Note:** this will need to be updated again, pending release of [enketo-core 6.0.4](https://github.com/enketo/enketo-core/pull/863)

- [x] Create release PR
- [ ] Check [Dependabot](https://github.com/enketo/enketo-express/security/dependabot) for alerts
  - **Note** this will not correctly reflect the vulnerabilities to be released until the dependency upgrades are merged. I do not see any vulnerabilities that aren't addressed with `npm audit` below.
- [x] Run `npm update`
    - [x] Check if `node-forge` has been updated and if so, verify encrypted submissions end-to-end
- [x] Run `npm audit`
    - [x] Run `npm audit fix --production` to apply most important fixes
      - **Note** there is an outstanding dependency vulnerability for `jstransformer-markdown-it`, which is only used to render `CHANGELOG.md` as HTML, which does not process arbitrary user input
- [x] Run `npm ci`
- [x] Run `npm test`
- [x] Run `npm run build-docs`
- [x] Update `CHANGELOG.md`
- [x] Update version in `package.json`
    - N/A: Bump to major version if consumers have to make changes.
- [ ] Merge PR with all changes @lognaturel
- [ ] Create GitHub release @lognaturel
- [ ] Tag and publish the release @lognaturel
    - GitHub Action will publish it to npm

### CODE REVIEW

**Comment by MartijnR** [comment]
Watch out for node-forge https://github.com/enketo/enketo-express/pull/378#issuecomment-1025766053. Just in the unlikely case, that users end up with encrypted records that can never be decrypted.

**Comment by eyelidlessness** [comment]
@MartijnR As @lognaturel [mentioned on the enketo-core PR](https://github.com/enketo/enketo-core/pull/859#pullrequestreview-869895367), I have verified the `node-forge` upgrade works with Central's managed encryption. I have now also verified that it works with non-managed public/private key encryption through ODK Briefcase, as you said in https://github.com/enketo/enketo-express/pull/378#issuecomment-1025766053

**Comment by MartijnR** [comment]
Great! Thanks!

**Comment by lognaturel** [comment]
Core 6.0.4 is released. I think https://github.com/enketo/enketo-express/pull/373 and https://github.com/enketo/enketo-express/pull/365 should also be merged.

Would be good to update the build status icon to use the Github action and to have that link to /actions or something (rather than to the icon itself which is what's going on in Core right now).

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
