### PR TITLE
Code style/formatting: Prettier + Airbnb ESLint preset

### LINKED ISSUE #328: Code style: reverse `space-in-parens` rule
The `space-in-parens: ["error", "always"]` ESLint rule enforces that function calls and other use of parentheses are formatted like:

```js
fn( param, ...params );
```

rather than:

```js
fn(param, ...params);
```

This style is a source of constant cognitive load:

- It's unidiomatic[^1], adding cognitive load due to its unfamiliarity
- It increases line length, and moves related things further apart
- It makes identifying and understanding syntax more difficult
- It frequently breaks editing flow, by interrupting facilities provided by editors like auto-closing/auto-wrapping parentheses

I would like to reverse this rule (`["error", "never"]`). I tried `npx grunt eslint:fix` on a local branch, and it successfully fixed all errors automatically, so my inclination is to make this change project-wide.

[^1]: Compare usage of [`["error", "always"...]`](https://sourcegraph.com/search?q=context:global+language:json+%5E%5Cs*%22space-in-parens%22:%5Cs*%5C%5B%5Cs*%22%28error%7Cwarn%29%22%5Cs*%2C%5Cs*%22always%22&patternType=regexp) to [`"error"` (defaults to `never`) or `["error", "never"...]`](https://sourcegraph.com/search?q=context:global+language:json+%5E%5Cs*%22space-in-parens%22:%28%22error%22%7C%5Cs*%5C%5B%5Cs*%22%28error%7Cwarn%29%22%5Cs*%2C%5Cs*%22never%22%29+count:100000&patternType=regexp))

### PR DESCRIPTION
**Pull request by eyelidlessness**
The purpose of this change is to move toward a more idiomatic code style, and automate as much of it as possible. What's in the change:

- Adds automatic formatting provided by [Prettier](https://prettier.io/)
- Consolidates all ESLint configs into one file via `overrides`
  - Overrides files run in a Node environment to specify that in ESLint config (removing arbitrary global declarations there and across several modules)
- Extends [Airbnb's ESLint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), a commonly used, opinionated set of rules
  - Overrides some of those rules to be warnings where they're not automatically fixable; there are _a lot of warnings_, the goal is to fix them wherever we touch code with warnings
  - Manually fixes a very small portion of those warnings where it was trivial and obviously safe (`no-redeclare` for Node globals, a couple of optional function params before required params which never receive `undefined`/never hit the fallback value)
- Extends Prettier's ESLint config to enable checking Prettier rules (e.g. while editing in VSCode and in CI)
- Applies automatic Prettier and ESLint formatting on save in VSCode

Closes #328.

Opened as draft while I do more manual testing.

#### I have verified this PR works with 

- [x] Online form submission
- [x] Offline form submission
- [x] Saving offline drafts
- [x] Submitting offline drafts
- [x] Editing submissions
- [x] Form preview
- [ ] None of the above

### CODE REVIEW

**Comment by eyelidlessness** [comment]
*Sigh*, I suspect the CI failure may be related to different behavior in `grunt` vs the default `eslint` behavior which is likely invoked by the pre-commit hook. Unfortunately that would mean these changes may differ from the changes I made directly. Will investigate further…

**Comment by lognaturel** [comment]
This looks great to me. There are a few rules I wouldn’t have picked myself, especially around line breaks, but I prefer using a broadly-accepted set of defaults that are automatically applied over making subjective decisions. #328 has been the only style issue I’ve felt significant pain from. 

Let’s give 1-2 days for anyone who watches this repo to comment as desired (especially @MartijnR).

**Comment by MartijnR** [comment]
Thank you! I'm planning to do a trial merge in OpenClinica today. I'm hoping `grunt eslint:fix` will fix most conflicts.

**Comment by MartijnR** [comment]
No problems. Thanks for the heads up!

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
