### PR TITLE
Generate encryption key at the root level of config.json if it does not exist.

### PR DESCRIPTION
**Pull request by noliveleger**
When `encryption key` is not present in `config.json`, a script at start-up generates a new one and injects it into the configuration file under `linked form and data server`.
According to the code, it should be at root level.

- https://github.com/enketo/enketo-express/blob/master/app/controllers/authentication-controller.js#L82
- https://github.com/enketo/enketo-express/blob/master/app/models/user-model.js#L24

### CODE REVIEW

**Comment by MartijnR** [comment]
I added @jnm as I don't really know docker.

**Comment by jnm** [comment]
I did the squash-and-merge wrong :confounded:
image

**Comment by MartijnR** [comment]
:open_mouth: OMG!! 

What did you do wrong though? I don't see it, so it's hard to determine the appropriate level of shaming and punishment. I do see a set of very sloppy commits just before that. We definitely have to restrict that user's committer privileges.

**Comment by MartijnR** [comment]
Aha! You are referring to the commit description! So you just broke a nice 9 year-run of extreme consistency! Tsssk. ;)

**Comment by jnm** [comment]
:sob: I thought I edited the commit message and erased the old ones, but apparently I was just editing everything below the first line!

**Comment by jnm** [comment]
OK, I understand the error of my ways!
image
:facepalm:

**Pull request merged**
