### PR TITLE
Feature/client config rewrite 163

### PR DESCRIPTION
**Pull request by MartijnR**

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
I'm not super familiar with all things Enketo so my review should be taken with a grain of salt. I did read through the general approach and theory [on this site by a very passionate person](https://immutablewebapps.org/) and the high level strategy sounds great. I verified that `env` is plumbed through as expected. I think the new docs are great and very clear. I did **not** actually run it.

**Comment by MartijnR** [comment]
Thanks for reviewing @lognaturel!

**Comment by lognaturel** [comment]
What are settings?

**Comment by MartijnR** [comment]
I'm not quite satisfied with the 'settings' terminology, but they include the client configuration + some webform-form-view-specific context 'settings': https://github.com/enketo/enketo-express/blob/master/public/js/src/module/settings.js, some of which can be set with query parameters.

**Comment by lognaturel** [comment]
Looks like this might have been squashed to master as acba08b?

**Comment by MartijnR** [comment]
Yes! Will close this now.

**Pull request closed without merging**
